server:
  port: 8080
  servlet:
    context-path:
spring:
  resources:
    static-locations: classpath:/templates/
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
